"""Ambisonic format helpers — normalisation and channel-order conversion.

The core of this package uses **orthonormal real / complex** SH (``∫|Y|²
dΩ = 1``) in **ACN** ordering internally.  Most commodity ambisonic
files instead use one of:

* **AmbiX** — ACN ordering with *SN3D* (Schmidt semi-normalised) or
  *N3D* (fully normalised) scaling.  This is the dominant format for
  modern VR/AR tools (Google/YouTube, Reaper, IEM Plug-in Suite, …).
* **FuMa** — B-format *Furse-Malham* ordering and normalisation,
  defined through 3rd order and used by the legacy B-format ecosystem
  (VVAudio, Bruce Wiggins, older VST plug-ins).

This module provides:

* :func:`convert_ambi_normalization` — rescale between
  ``orthonormal`` / ``n3d`` / ``sn3d`` (all ACN-ordered).
* :func:`acn_to_fuma` / :func:`fuma_to_acn` — reorder and rescale
  between ACN-SN3D and FuMa (through 3rd order).

Higher-order FuMa is not standardised; those entry points raise
``ValueError`` past order 3.
"""

from .encoder import encode_plane_wave, encode_plane_wave_frame
from .format import (
    acn_to_fuma,
    convert_ambi_normalization,
    fuma_to_acn,
)
from .channels import (
    AmbisonicChannel,
    MixedOrderSpec,
    acn_to_fuma_permutation,
    acn_sequence,
    active_channel_indices,
    active_channel_mask,
    active_channel_report,
    channel_degree_order,
    channel_degrees,
    channel_energy,
    channel_index,
    channel_label_to_acn,
    channel_labels,
    channel_metadata_dicts,
    channel_name,
    channel_orders,
    channel_peak,
    channel_rms,
    channel_table,
    combine_channel_masks,
    compact_mixed_order_coeffs,
    degree_channel_indices,
    degree_mask,
    drop_channels,
    expand_mixed_order_coeffs,
    first_acn_for_degree,
    first_order_channel_mask,
    fuma_to_acn_permutation,
    fuma_channel_labels,
    horizontal_channel_indices,
    horizontal_channel_mask,
    infer_mixed_order,
    indices_to_mask,
    invert_channel_mask,
    join_coeffs_by_order,
    last_acn_for_degree,
    mask_to_indices,
    mixed_order_channel_count,
    mixed_order_channel_indices,
    mixed_order_mask,
    non_omni_channel_mask,
    omni_channel_mask,
    order_block_slice,
    order_block_start,
    order_block_stop,
    order_weight_vector,
    per_order_channel_counts,
    per_order_energy_fraction,
    per_order_peak,
    per_order_rms,
    reorder_acn_to_fuma,
    reorder_fuma_to_acn,
    sectoral_channel_indices,
    sectoral_channel_mask,
    select_channels,
    signed_order_channel_indices,
    signed_order_mask,
    split_coeffs_by_order,
    truncate_channel_mask,
    validate_ambisonic_channel_axis,
    validate_channel_indices,
    validate_channel_mask,
    zero_channels,
    zonal_channel_indices,
    zonal_channel_mask,
)
from .intensity import doa_from_intensity, intensity_vector
from .io import read_ambix_frame, read_ambix_wav, write_ambix_frame, write_ambix_wav
from .nfc import nfc_hoa_distance_filter
from .processing import (
    ambi_peak,
    ambi_rms,
    apply_channel_gains,
    apply_per_order_gains,
    change_order,
    channel_correlation,
    channel_covariance,
    ensure_channel_axis,
    fade_ambi_frames,
    mix_ambi_frames,
    mono_from_w,
    move_channel_axis,
    normalize_peak,
    normalize_rms,
    order_balance_db,
    order_rms,
    pad_order,
    per_order_gains,
    truncate_order,
    w_channel,
)
from .spec import (
    AmbisonicFrame,
    AmbisonicSignalReport,
    AmbisonicSpec,
    ambisonic_signal_report,
    channel_count,
    infer_order,
    order_channel_mask,
    order_channel_slices,
    per_order_energy,
)
from .translation import translate_foa
from .uhj import uhj_decode, uhj_encode

__all__ = [
    "acn_to_fuma",
    "acn_to_fuma_permutation",
    "acn_sequence",
    "active_channel_indices",
    "active_channel_mask",
    "active_channel_report",
    "ambi_peak",
    "ambi_rms",
    "AmbisonicChannel",
    "AmbisonicFrame",
    "AmbisonicSignalReport",
    "AmbisonicSpec",
    "ambisonic_signal_report",
    "apply_channel_gains",
    "apply_per_order_gains",
    "change_order",
    "channel_count",
    "channel_correlation",
    "channel_covariance",
    "channel_degree_order",
    "channel_degrees",
    "channel_energy",
    "channel_index",
    "channel_label_to_acn",
    "channel_labels",
    "channel_metadata_dicts",
    "channel_name",
    "channel_orders",
    "channel_peak",
    "channel_rms",
    "channel_table",
    "combine_channel_masks",
    "compact_mixed_order_coeffs",
    "convert_ambi_normalization",
    "degree_channel_indices",
    "degree_mask",
    "doa_from_intensity",
    "drop_channels",
    "encode_plane_wave",
    "encode_plane_wave_frame",
    "ensure_channel_axis",
    "expand_mixed_order_coeffs",
    "fade_ambi_frames",
    "first_acn_for_degree",
    "first_order_channel_mask",
    "fuma_to_acn",
    "fuma_to_acn_permutation",
    "fuma_channel_labels",
    "horizontal_channel_indices",
    "horizontal_channel_mask",
    "infer_order",
    "infer_mixed_order",
    "indices_to_mask",
    "invert_channel_mask",
    "intensity_vector",
    "join_coeffs_by_order",
    "last_acn_for_degree",
    "mask_to_indices",
    "mix_ambi_frames",
    "MixedOrderSpec",
    "mixed_order_channel_count",
    "mixed_order_channel_indices",
    "mixed_order_mask",
    "mono_from_w",
    "move_channel_axis",
    "nfc_hoa_distance_filter",
    "non_omni_channel_mask",
    "normalize_peak",
    "normalize_rms",
    "omni_channel_mask",
    "order_balance_db",
    "order_block_slice",
    "order_block_start",
    "order_block_stop",
    "order_channel_mask",
    "order_channel_slices",
    "order_rms",
    "order_weight_vector",
    "pad_order",
    "per_order_channel_counts",
    "per_order_energy",
    "per_order_energy_fraction",
    "per_order_gains",
    "per_order_peak",
    "per_order_rms",
    "read_ambix_wav",
    "read_ambix_frame",
    "reorder_acn_to_fuma",
    "reorder_fuma_to_acn",
    "sectoral_channel_indices",
    "sectoral_channel_mask",
    "select_channels",
    "signed_order_channel_indices",
    "signed_order_mask",
    "split_coeffs_by_order",
    "truncate_channel_mask",
    "truncate_order",
    "translate_foa",
    "uhj_decode",
    "uhj_encode",
    "validate_ambisonic_channel_axis",
    "validate_channel_indices",
    "validate_channel_mask",
    "w_channel",
    "zero_channels",
    "write_ambix_wav",
    "write_ambix_frame",
    "zonal_channel_indices",
    "zonal_channel_mask",
]
