"""Room acoustic simulators for SH-domain testing.

The shoebox image-source method (Allen & Berkley 1979) produces an
ambisonic room impulse response at a chosen listener position, using
rectangular-room geometry and per-wall reflection coefficients.  It
is the standard baseline for reverberant DOA / beamforming
experiments because it is parametric, reproducible, and fast.
"""

from .banded import shoebox_rir_banded
from .design import (
    RoomDesignTarget,
    absorption_budget_per_surface,
    bolt_area_score,
    count_modes_in_band,
    critical_distance_for_target,
    is_inside_bolt_area,
    mean_absorption_to_reflection,
    modal_density_per_hz,
    modal_density_weyl,
    modal_overlap_factor,
    reflection_to_mean_absorption,
    room_constant_for_target,
    room_design_target,
    room_ratio,
    rt_constant,
    target_absorption_area_sabine,
    target_mean_absorption_eyring,
    target_mean_absorption_sabine,
    target_uniform_reflection_eyring,
    target_uniform_reflection_sabine,
    verify_target_rt60,
)
from .fdn import fdn_reverb, fdn_sh_tail
from .metrics import (
    RIRMetrics,
    banded_rir_metrics,
    center_time,
    clarity,
    definition,
    direct_to_reverberant_ratio,
    early_decay_time,
    early_late_energy,
    energy_decay_curve,
    interaural_cross_correlation,
    lateral_energy_fraction,
    reverberation_time,
    reverberation_times,
    rir_metrics,
    strength,
    total_energy,
)
from .reverb import convolve_mono_to_ambi, convolve_sh_to_sh
from .shoebox import (
    ShoeboxRoom,
    shoebox_rir,
    shoebox_sh_rir,
)
from .statistical import (
    ShoeboxAcousticStats,
    air_absorption_attenuation_iso9613,
    air_absorption_coefficient_iso9613,
    arau_puchades_rt60,
    classify_room_modes,
    critical_distance,
    critical_distance_from_rt60,
    equivalent_absorption_area,
    eyring_rt60,
    mean_absorption,
    millington_sette_rt60,
    rectangular_room_modes,
    room_constant,
    sabine_rt60,
    schroeder_frequency,
    shoebox_acoustic_stats,
    shoebox_axis_surface_areas,
    shoebox_surface_areas,
    shoebox_volume,
)

__all__ = [
    "RIRMetrics",
    "RoomDesignTarget",
    "ShoeboxAcousticStats",
    "ShoeboxRoom",
    "absorption_budget_per_surface",
    "air_absorption_attenuation_iso9613",
    "air_absorption_coefficient_iso9613",
    "arau_puchades_rt60",
    "banded_rir_metrics",
    "bolt_area_score",
    "center_time",
    "classify_room_modes",
    "clarity",
    "convolve_mono_to_ambi",
    "convolve_sh_to_sh",
    "count_modes_in_band",
    "critical_distance",
    "critical_distance_for_target",
    "critical_distance_from_rt60",
    "definition",
    "direct_to_reverberant_ratio",
    "early_decay_time",
    "early_late_energy",
    "energy_decay_curve",
    "equivalent_absorption_area",
    "eyring_rt60",
    "fdn_reverb",
    "fdn_sh_tail",
    "interaural_cross_correlation",
    "is_inside_bolt_area",
    "lateral_energy_fraction",
    "mean_absorption",
    "mean_absorption_to_reflection",
    "millington_sette_rt60",
    "modal_density_per_hz",
    "modal_density_weyl",
    "modal_overlap_factor",
    "rectangular_room_modes",
    "reflection_to_mean_absorption",
    "reverberation_time",
    "reverberation_times",
    "rir_metrics",
    "room_constant",
    "room_constant_for_target",
    "room_design_target",
    "room_ratio",
    "rt_constant",
    "sabine_rt60",
    "schroeder_frequency",
    "shoebox_acoustic_stats",
    "shoebox_axis_surface_areas",
    "shoebox_rir",
    "shoebox_rir_banded",
    "shoebox_sh_rir",
    "shoebox_surface_areas",
    "shoebox_volume",
    "strength",
    "target_absorption_area_sabine",
    "target_mean_absorption_eyring",
    "target_mean_absorption_sabine",
    "target_uniform_reflection_eyring",
    "target_uniform_reflection_sabine",
    "total_energy",
    "verify_target_rt60",
]
